USE [Northwind]
GO
/****** Object:  StoredProcedure [dbo].[EMPLOYEEDATAWITHCURSOR]    Script Date: 9/9/2019 1:47:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[EMPLOYEEDATAWITHCURSOR] 
(
	@EMPID INT
)  
AS
BEGIN

	DECLARE @EmployeeID INT
	DECLARE @FirstName VARCHAR(MAX)
	DECLARE @LastName VARCHAR(MAX)

	-- DECLARE THE CURSOR TO 
	DECLARE EMPLOYEE_CURSOR CURSOR
	FOR	SELECT * FROM [dbo].[TABLEVALUEeXAMPLE](@EMPID)

	--OPENING A CURSOR
	OPEN EMPLOYEE_CURSOR 

	--FETCHING THE TABLE VALUED DATA FROM THE CURSOR 
	FETCH NEXT FROM EMPLOYEE_CURSOR INTO @EmployeeID, @FirstName, @LastName

	-- CONDITION TO CHECK THE ROWS LEFT INSIDE THE CURSOR (BIT TYPE/ BOOLEAN)
	WHILE @@FETCH_STATUS = 0 
	BEGIN
		PRINT	'EMPLOYEE DATABASE'
		PRINT	'EMPLOYEE ID: ' + CAST (@EmployeeID AS VARCHAR(MAX)) +
				' EMPLOYEE FIRST NAME: ' + @FirstName + 
				' EMPLOYEE LAST NAME: ' + @LastName
		
		--FETCHING THE TABLE VALUED DATA FROM THE CURSOR 
		FETCH NEXT FROM EMPLOYEE_CURSOR INTO @EmployeeID, @FirstName, @LastName
	END

	--CLOSING A CURSOR
	CLOSE EMPLOYEE_CURSOR

	--DEALLOCATION OF THE CURSOR
	DEALLOCATE EMPLOYEE_CURSOR
	RETURN 1
END
